name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Ruby setup
      uses: actions/setup-ruby@v1.0.0

    - name: Bundle install
      run: | 
        gem install bundler 
        bundle install
    - name: Build Jekyll
      run: |
        bundle exec jekyll build --config _config.release.yml
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{secrets.FTP_HOST}}
        user: ${{secrets.FTP_LOGIN}}
        # FTP password
        password: ${{secrets.FTP_PASSWORD}}
        forceSsl: true
        localDir: ./_site
        remoteDir: ./khoawebmaster
