name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push: 
    branches: ["release"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install environment
      uses: ruby/setup-ruby@v1.52.0
      with:
        bundler-cache: true
        ruby-version: 2.7 
        
    - name: Build Jekyll
      run: |
        bundle exec jekyll build --config _config.release.yml
        
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{secrets.FTP_HOST}}
        user: ${{secrets.FTP_LOGIN}}
        # FTP password
        password: ${{secrets.FTP_PASSWORD}}
        forceSsl: true
        localDir: ./_site
        remoteDir: .
        
    - name: Deployment 
      # You may pin to the exact commit or the version.
      # uses: chrnorm/deployment-action@0a0479c8ab41cd336ddc266342ca0a1c54727a72
      uses: chrnorm/deployment-action@v1.2.0
      with:
        # Initial status for the deployment
        initial_status: 'success'
        # The reference for the deployment
        ref: # optional
        # Github repository token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Target url location
        target_url: 'https://klahanie.com'
        # Descriptive message about the deployment
        description: 'Deployed $GITHUB_SHA to production'
        # The name of the environment for the deployment
        environment: 'Production'

